### ISSUE TITLE
Something that might interest you

### ISSUE THREAD

**Issue by jacobtread** [Aim4kill/BlazeSDK#3]
Hey, I've had a gold mine recently brought to my attention which I think would greatly help this project if you haven't already found out about it (Its some source code that got out) give me a contact on discord "jacobtread" and i'll be happy to share it with you

**Comment by Aim4kill** [comment]
Hi, i wrote to you, but
![image](https://github.com/Aim4kill/BlazeSDK/assets/76944477/b981a3ea-eaf0-4b84-9521-a397da11e82e)

which is why sent a friend request too, when you accept will resend the message.
